### ISSUE TITLE
ADR0003 - Implementation Log

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/architectural-decision-log#3]
This issue acts as the implementation log for ADR0003 

Any work towards implementing this decision  should be linked to this issue using Issue or PR comments 

A single maintainer must be assigned to the log as the owner of the implementation. When they feel the decision has been implemented they will close the log

**Comment by RossMurr4y** [comment]
Shall we setup a GitHub Issue template for this? If so I am happy to put together a draft for review.

**Comment by roleyfoley** [comment]
Yeah was thinking an issue template and updating the template.md file. I hadn't started as the ADR hasn't be accepted yet

**Comment by RossMurr4y** [comment]
Ah, I thought it had as its listed as `status: accepted`. Doesn't the existence of this ticket mean it's accepted?

**Comment by roleyfoley** [comment]
Log template has been accepted and used for the last few ADR's will call this done
